#pragma once
#ifndef SEQ_USE_HANDLES
#define SEQ_USE_HANDLES 0
#endif

#ifndef BRICK_EXPERIMENTAL_PATTERN_CODEC_V2
#define BRICK_EXPERIMENTAL_PATTERN_CODEC_V2 0
#endif

#ifndef SEQ_ENABLE_COLD_SECTIONS
#define SEQ_ENABLE_COLD_SECTIONS 0
#endif

#ifndef SEQ_ENABLE_HOT_SECTIONS
#define SEQ_ENABLE_HOT_SECTIONS 0
#endif

#ifndef SEQ_EXPERIMENT_MOVE_ONE_BLOCK
#define SEQ_EXPERIMENT_MOVE_ONE_BLOCK 0
#endif
